language: go
dist: focal

stages:
  - build
  - deploy

go:
  - "1.15"

jobs:
  include:
    - name: Go Build
      stage: build
      script:
        - go mod download
        - go build .

    - name: Docker build
      stage: deploy
      before_script:
        - chmod -R u+x ./scripts/deploy.sh
      script:
        - ./scripts/deploy.sh