name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Dockerfile Validator
      # You may pin to the exact commit or the version.
      # uses: ghe-actions/dockerfile-validator@56a2d2c1cfaf01166323ff53a4765ec5342bd9d4
      uses: ghe-actions/dockerfile-validator@v1.6
      
    - name: Build the Docker image for (linux/amd64, linux/arm64 & linux/arm/v7)
      run: ./scripts/deploy.sh

    - name: Aqua Security Trivy
      # You may pin to the exact commit or the version.
      # uses: aquasecurity/trivy-action@2b5de510862c22b735aa586acbafe850cfe75148
      uses: aquasecurity/trivy-action@0.0.8
      with:
        # image reference
        image-ref: zbozzo/knx-prometheus-exporter
